/**
 * Demonstration data loaded into SQLite the first time the backend starts
 * against an empty database (see `./seed.ts`). Shapes match `./types.ts`.
 */

import type {
  Appointment,
  AuditLog,
  ClinicalVisit,
  EyeExamination,
  InsuranceClaim,
  InsuranceProvider,
  InventoryTransaction,
  Invoice,
  Patient,
  Payment,
  PracticeSettings,
  Prescription,
  Product,
  QueueEntry,
  RefractionValues,
  Role,
  Supplier,
  User,
} from "./types.ts";

export const today = (): string => new Date().toISOString().slice(0, 10);

const daysAgo = (n: number): string => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
};

const isoDaysAgo = (n: number, hour = 10): string => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(hour, 15, 0, 0);
  return d.toISOString();
};

export const roles: Role[] = [
  {
    id: "administrator",
    name: "Administrator",
    description: "Full access to every module including users and settings.",
    modules: [
      "dashboard",
      "patients",
      "appointments",
      "queue",
      "clinical",
      "prescriptions",
      "invoices",
      "payments",
      "insurance",
      "inventory",
      "suppliers",
      "reports",
      "administration",
      "settings",
    ],
  },
  {
    id: "receptionist",
    name: "Receptionist / Front Desk",
    description: "Registers patients, books appointments and manages the queue.",
    modules: ["dashboard", "patients", "appointments", "queue", "invoices"],
  },
  {
    id: "optometrist",
    name: "Optometrist / Clinician",
    description: "Runs eye examinations and issues prescriptions.",
    modules: [
      "dashboard",
      "patients",
      "appointments",
      "queue",
      "clinical",
      "prescriptions",
      "reports",
    ],
  },
  {
    id: "cashier",
    name: "Cashier / Accounts",
    description: "Handles invoicing, payments, receipts and insurance claims.",
    modules: ["dashboard", "patients", "invoices", "payments", "insurance", "reports"],
  },
  {
    id: "store_officer",
    name: "Inventory / Store Officer",
    description: "Manages optical stock, suppliers and stock movements.",
    modules: ["dashboard", "inventory", "suppliers", "reports"],
  },
];

export const users: User[] = [
  {
    id: "u1",
    fullName: "Dr. Grace Wanjiru",
    email: "grace.wanjiru@amanieye.co.ke",
    username: "gwanjiru",
    phone: "0722 145 880",
    role: "administrator",
    status: "active",
    lastLogin: isoDaysAgo(0, 7),
    createdAt: isoDaysAgo(420),
  },
  {
    id: "u2",
    fullName: "Dr. Amina Otieno",
    email: "amina.otieno@amanieye.co.ke",
    username: "aotieno",
    phone: "0733 902 118",
    role: "optometrist",
    status: "active",
    lastLogin: isoDaysAgo(0, 8),
    createdAt: isoDaysAgo(300),
  },
  {
    id: "u3",
    fullName: "Brian Kimani",
    email: "brian.kimani@amanieye.co.ke",
    username: "bkimani",
    phone: "0701 220 451",
    role: "receptionist",
    status: "active",
    lastLogin: isoDaysAgo(0, 7),
    createdAt: isoDaysAgo(260),
  },
  {
    id: "u4",
    fullName: "Mercy Chebet",
    email: "mercy.chebet@amanieye.co.ke",
    username: "mchebet",
    phone: "0745 118 902",
    role: "cashier",
    status: "active",
    lastLogin: isoDaysAgo(1, 16),
    createdAt: isoDaysAgo(190),
  },
  {
    id: "u5",
    fullName: "Joseph Barasa",
    email: "joseph.barasa@amanieye.co.ke",
    username: "jbarasa",
    phone: "0798 441 207",
    role: "store_officer",
    status: "active",
    lastLogin: isoDaysAgo(2, 11),
    createdAt: isoDaysAgo(150),
  },
  {
    id: "u6",
    fullName: "Dr. Samuel Kiprotich",
    email: "samuel.kiprotich@amanieye.co.ke",
    username: "skiprotich",
    phone: "0712 664 330",
    role: "optometrist",
    status: "disabled",
    lastLogin: isoDaysAgo(64, 12),
    createdAt: isoDaysAgo(320),
  },
];

export const clinicians = users.filter(
  (u) => u.role === "optometrist" || u.role === "administrator",
);

export const insuranceProviders: InsuranceProvider[] = [
  {
    id: "ins1",
    name: "NHIF",
    code: "NHIF",
    contactPerson: "Claims Desk",
    phone: "0800 720 601",
    email: "claims@nhif.or.ke",
    coverageNotes: "Optical benefit KES 6,000 per member per year.",
    status: "active",
  },
  {
    id: "ins2",
    name: "AAR Insurance",
    code: "AAR",
    contactPerson: "Linet Wambui",
    phone: "0709 911 000",
    email: "optical@aar.co.ke",
    coverageNotes: "Frames capped at KES 12,000. Pre-authorisation required.",
    status: "active",
  },
  {
    id: "ins3",
    name: "Jubilee Health",
    code: "JUB",
    contactPerson: "Peter Njoroge",
    phone: "0709 949 000",
    email: "health.claims@jubileekenya.com",
    coverageNotes: "20% co-payment on lenses.",
    status: "active",
  },
  {
    id: "ins4",
    name: "Britam",
    code: "BRT",
    contactPerson: "Faith Mwende",
    phone: "0705 100 100",
    email: "claims@britam.com",
    coverageNotes: "Annual optical limit KES 15,000.",
    status: "inactive",
  },
];

export const patients: Patient[] = [
  {
    id: "p1",
    patientNumber: "AE-2026-0188",
    firstName: "Wanjiku",
    middleName: "Njeri",
    lastName: "Kamau",
    dateOfBirth: "1991-03-12",
    gender: "female",
    nationalId: "28114552",
    phone: "0722 334 881",
    altPhone: "0733 112 004",
    email: "wanjiku.kamau@gmail.com",
    county: "Nairobi",
    town: "Westlands",
    address: "Mvuli Road, Apt 4B",
    emergencyContact: { name: "Peter Kamau", relationship: "Spouse", phone: "0720 445 118" },
    occupation: "Accountant",
    referralSource: "Walk-in",
    insuranceProviderId: "ins2",
    insuranceMemberNumber: "AAR-884221",
    notes: "Long screen hours, reports end-of-day eye strain.",
    status: "active",
    registeredAt: isoDaysAgo(410),
    lastVisitAt: isoDaysAgo(0, 9),
  },
  {
    id: "p2",
    patientNumber: "AE-2026-0189",
    firstName: "Peter",
    lastName: "Otieno",
    dateOfBirth: "1978-07-24",
    gender: "male",
    nationalId: "21445780",
    phone: "0701 220 451",
    email: "p.otieno@yahoo.com",
    county: "Kisumu",
    town: "Milimani",
    address: "Oginga Odinga Street",
    emergencyContact: { name: "Rose Otieno", relationship: "Sister", phone: "0711 003 220" },
    occupation: "Teacher",
    referralSource: "Referred by Dr. Mwangi",
    insuranceProviderId: "ins1",
    insuranceMemberNumber: "NHIF-5521884",
    status: "active",
    registeredAt: isoDaysAgo(240),
    lastVisitAt: isoDaysAgo(1, 11),
  },
  {
    id: "p3",
    patientNumber: "AE-2026-0190",
    firstName: "Achieng",
    middleName: "Grace",
    lastName: "Njeri",
    dateOfBirth: "1965-11-02",
    gender: "female",
    nationalId: "10228455",
    phone: "0733 902 118",
    county: "Nairobi",
    town: "Kasarani",
    emergencyContact: { name: "Alice Njeri", relationship: "Daughter", phone: "0798 220 114" },
    occupation: "Trader",
    referralSource: "Community outreach",
    notes: "Diabetic since 2014 — annual retinal review required.",
    status: "active",
    registeredAt: isoDaysAgo(700),
    lastVisitAt: isoDaysAgo(2, 10),
  },
  {
    id: "p4",
    patientNumber: "AE-2026-0191",
    firstName: "Mwangi",
    lastName: "Barasa",
    dateOfBirth: "1999-01-19",
    gender: "male",
    phone: "0745 118 902",
    email: "mbarasa99@gmail.com",
    county: "Nakuru",
    town: "Lanet",
    emergencyContact: { name: "Susan Barasa", relationship: "Mother", phone: "0720 998 441" },
    occupation: "Student",
    referralSource: "Instagram",
    status: "active",
    registeredAt: isoDaysAgo(95),
    lastVisitAt: isoDaysAgo(4, 14),
  },
  {
    id: "p5",
    patientNumber: "AE-2026-0192",
    firstName: "Chebet",
    lastName: "Korir",
    dateOfBirth: "1985-06-08",
    gender: "female",
    nationalId: "24558120",
    phone: "0798 441 207",
    email: "chebet.korir@outlook.com",
    county: "Kericho",
    town: "Ainamoi",
    emergencyContact: { name: "Daniel Korir", relationship: "Spouse", phone: "0712 664 330" },
    occupation: "Nurse",
    referralSource: "Employer scheme",
    insuranceProviderId: "ins3",
    insuranceMemberNumber: "JUB-772100",
    status: "active",
    registeredAt: isoDaysAgo(150),
    lastVisitAt: isoDaysAgo(0, 8),
  },
  {
    id: "p6",
    patientNumber: "AE-2026-0193",
    firstName: "Joseph",
    middleName: "Kipchoge",
    lastName: "Leks",
    dateOfBirth: "1972-09-30",
    gender: "male",
    nationalId: "14887220",
    phone: "0720 118 445",
    county: "Uasin Gishu",
    town: "Eldoret",
    emergencyContact: { name: "Naomi Leks", relationship: "Spouse", phone: "0733 445 118" },
    occupation: "Athletics coach",
    referralSource: "Walk-in",
    notes: "Contact lens wearer, prefers monthly disposables.",
    status: "active",
    registeredAt: isoDaysAgo(520),
    lastVisitAt: isoDaysAgo(7, 9),
  },
  {
    id: "p7",
    patientNumber: "AE-2026-0194",
    firstName: "Patricia",
    lastName: "Mwangi",
    dateOfBirth: "2004-02-14",
    gender: "female",
    phone: "0711 552 908",
    county: "Kiambu",
    town: "Ruiru",
    emergencyContact: { name: "Jane Mwangi", relationship: "Mother", phone: "0722 908 114" },
    occupation: "Student",
    referralSource: "School screening",
    status: "active",
    registeredAt: isoDaysAgo(12),
    lastVisitAt: null,
  },
  {
    id: "p8",
    patientNumber: "AE-2026-0195",
    firstName: "Amara",
    lastName: "Njoroge",
    dateOfBirth: "1988-12-05",
    gender: "female",
    nationalId: "26114880",
    phone: "0707 441 220",
    email: "amara.njoroge@gmail.com",
    county: "Mombasa",
    town: "Nyali",
    emergencyContact: { name: "Kevin Njoroge", relationship: "Brother", phone: "0745 220 118" },
    occupation: "Hotel manager",
    referralSource: "Walk-in",
    insuranceProviderId: "ins2",
    insuranceMemberNumber: "AAR-110552",
    status: "active",
    registeredAt: isoDaysAgo(60),
    lastVisitAt: isoDaysAgo(0, 9),
  },
  {
    id: "p9",
    patientNumber: "AE-2026-0196",
    firstName: "Daniel",
    lastName: "Mutiso",
    dateOfBirth: "1959-04-21",
    gender: "male",
    nationalId: "8822114",
    phone: "0714 220 665",
    county: "Machakos",
    town: "Machakos Town",
    emergencyContact: { name: "Esther Mutiso", relationship: "Spouse", phone: "0722 110 884" },
    occupation: "Retired civil servant",
    referralSource: "Referral",
    notes: "Post cataract surgery (left eye, 2024).",
    status: "active",
    registeredAt: isoDaysAgo(330),
    lastVisitAt: isoDaysAgo(9, 15),
  },
  {
    id: "p10",
    patientNumber: "AE-2026-0197",
    firstName: "Halima",
    lastName: "Yusuf",
    dateOfBirth: "1996-08-17",
    gender: "female",
    phone: "0759 118 220",
    county: "Garissa",
    town: "Garissa Town",
    emergencyContact: { name: "Ali Yusuf", relationship: "Father", phone: "0733 220 118" },
    occupation: "Pharmacist",
    referralSource: "Walk-in",
    status: "archived",
    registeredAt: isoDaysAgo(640),
    lastVisitAt: isoDaysAgo(200, 12),
  },
];

const t = today();

export const appointments: Appointment[] = [
  {
    id: "a1",
    patientId: "p8",
    date: t,
    time: "09:00",
    clinicianId: "u2",
    type: "review",
    reason: "Phoria assessment",
    status: "in_consultation",
    createdAt: isoDaysAgo(6),
  },
  {
    id: "a2",
    patientId: "p6",
    date: t,
    time: "09:30",
    clinicianId: "u2",
    type: "contact_lens_fitting",
    reason: "Monthly lens refit",
    status: "waiting",
    createdAt: isoDaysAgo(5),
  },
  {
    id: "a3",
    patientId: "p7",
    date: t,
    time: "10:15",
    clinicianId: "u1",
    type: "new_consultation",
    reason: "First full eye examination",
    status: "checked_in",
    createdAt: isoDaysAgo(3),
  },
  {
    id: "a4",
    patientId: "p9",
    date: t,
    time: "11:00",
    clinicianId: "u1",
    type: "follow_up",
    reason: "Cataract follow-up (OS)",
    status: "confirmed",
    createdAt: isoDaysAgo(2),
  },
  {
    id: "a5",
    patientId: "p1",
    date: t,
    time: "08:30",
    clinicianId: "u2",
    type: "eye_test",
    reason: "Blurred distance vision",
    status: "completed",
    createdAt: isoDaysAgo(8),
  },
  {
    id: "a6",
    patientId: "p5",
    date: t,
    time: "08:00",
    clinicianId: "u2",
    type: "review",
    reason: "Spectacle comfort review",
    status: "completed",
    createdAt: isoDaysAgo(10),
  },
  {
    id: "a7",
    patientId: "p4",
    date: t,
    time: "14:00",
    clinicianId: "u1",
    type: "spectacle_collection",
    reason: "Collect new spectacles",
    status: "scheduled",
    createdAt: isoDaysAgo(4),
  },
  {
    id: "a8",
    patientId: "p3",
    date: t,
    time: "15:30",
    clinicianId: "u2",
    type: "follow_up",
    reason: "Diabetic retinal review",
    status: "scheduled",
    createdAt: isoDaysAgo(20),
  },
  {
    id: "a9",
    patientId: "p2",
    date: daysAgo(-1),
    time: "10:00",
    clinicianId: "u1",
    type: "review",
    reason: "Prescription recheck",
    status: "scheduled",
    createdAt: isoDaysAgo(1),
  },
  {
    id: "a10",
    patientId: "p4",
    date: daysAgo(-2),
    time: "11:30",
    clinicianId: "u2",
    type: "eye_test",
    reason: "Annual eye test",
    status: "scheduled",
    createdAt: isoDaysAgo(1),
  },
  {
    id: "a11",
    patientId: "p3",
    date: daysAgo(3),
    time: "09:45",
    clinicianId: "u2",
    type: "review",
    reason: "IOP check",
    status: "no_show",
    createdAt: isoDaysAgo(12),
  },
  {
    id: "a12",
    patientId: "p10",
    date: daysAgo(5),
    time: "13:00",
    clinicianId: "u1",
    type: "new_consultation",
    reason: "Headaches when reading",
    status: "cancelled",
    createdAt: isoDaysAgo(14),
  },
];

export const queue: QueueEntry[] = [
  {
    id: "q1",
    patientId: "p8",
    appointmentId: "a1",
    queueNumber: 9,
    arrivalTime: "08:44",
    appointmentTime: "09:00",
    clinicianId: "u2",
    status: "in_consultation",
    date: t,
  },
  {
    id: "q2",
    patientId: "p6",
    appointmentId: "a2",
    queueNumber: 10,
    arrivalTime: "09:05",
    appointmentTime: "09:30",
    clinicianId: "u2",
    status: "waiting",
    date: t,
  },
  {
    id: "q3",
    patientId: "p7",
    appointmentId: "a3",
    queueNumber: 11,
    arrivalTime: "09:52",
    appointmentTime: "10:15",
    clinicianId: "u1",
    status: "checked_in",
    date: t,
  },
  {
    id: "q4",
    patientId: "p1",
    appointmentId: "a5",
    queueNumber: 7,
    arrivalTime: "08:12",
    appointmentTime: "08:30",
    clinicianId: "u2",
    status: "completed",
    date: t,
  },
  {
    id: "q5",
    patientId: "p5",
    appointmentId: "a6",
    queueNumber: 6,
    arrivalTime: "07:48",
    appointmentTime: "08:00",
    clinicianId: "u2",
    status: "completed",
    date: t,
  },
];

const rx = (
  sphere: string,
  cylinder: string,
  axis: string,
  add = "0.00",
  va = "6/6",
): RefractionValues => ({ sphere, cylinder, axis, add, prism: "", va });

const examFor = (
  odS: string,
  osS: string,
  odC: string,
  osC: string,
): EyeExamination => ({
  visualAcuity: {
    unaidedOd: "6/18",
    unaidedOs: "6/24",
    unaidedNear: "N8",
    aidedOd: "6/6",
    aidedOs: "6/6",
    pinholeOd: "6/9",
    pinholeOs: "6/9",
  },
  refraction: {
    unaided: { od: rx("", "", "", "0.00", "6/18"), os: rx("", "", "", "0.00", "6/24") },
    objective: { od: rx(odS, odC, "175"), os: rx(osS, osC, "008") },
    subjective: { od: rx(odS, odC, "178"), os: rx(osS, osC, "008") },
    final: { od: rx(odS, odC, "178"), os: rx(osS, osC, "008") },
  },
  pd: "62",
  nearPd: "59",
  binocularVision: "Orthophoric at distance, 4 exophoria at near",
  colourVision: "Normal (Ishihara 12/12)",
  ocularMotility: "Full, smooth and comitant",
  pupils: "PERRLA, no RAPD",
  anteriorSegment: "Clear cornea, quiet anterior chamber, lens clear",
  posteriorSegment: "Healthy discs, CD ratio 0.3, flat maculae",
  iopOd: "14",
  iopOs: "15",
  keratometry: "43.25 / 44.00 @ 175",
  contactLensNotes: "",
});

export const visits: ClinicalVisit[] = [
  {
    id: "v1",
    visitNumber: "VIS-2026-0451",
    patientId: "p1",
    clinicianId: "u2",
    date: t,
    status: "completed",
    chiefComplaint: {
      reason: "Blurred distance vision",
      symptoms: "Squinting at road signs, headaches after screen work",
      duration: "4 months",
      previousEyeProblems: "Mild myopia diagnosed 2019",
      patientConcerns: "Wants thinner lenses for daily wear",
    },
    medicalHistory: {
      general: "Generally fit",
      medications: "None",
      allergies: "No known drug allergies",
      conditions: "None reported",
      surgeries: "None",
      familyHistory: "Mother wears spectacles for myopia",
    },
    ocularHistory: {
      conditions: "Myopia",
      surgery: "None",
      correction: "Single vision spectacles since 2019",
      lastExam: "March 2025",
      other: "No contact lens experience",
    },
    examination: examFor("-2.25", "-2.50", "-0.75", "-1.00"),
    diagnoses: [
      { description: "Compound myopic astigmatism", eye: "ou", code: "H52.2" },
      { description: "Digital eye strain", eye: "ou" },
    ],
    findings: "Stable anterior and posterior segments. Refractive error progressed by 0.25D.",
    assessment: "Myopic astigmatism requiring updated correction.",
    managementPlan: "New single vision spectacles with anti-reflective coating. Screen hygiene advice.",
    followUpDate: daysAgo(-365),
    clinicalNotes: "Discussed 20-20-20 rule and lighting.",
    createdAt: isoDaysAgo(0, 9),
  },
  {
    id: "v2",
    visitNumber: "VIS-2026-0448",
    patientId: "p3",
    clinicianId: "u2",
    date: daysAgo(2),
    status: "completed",
    chiefComplaint: {
      reason: "Annual diabetic eye review",
      symptoms: "Occasional floaters",
      duration: "Ongoing",
      previousEyeProblems: "Mild background retinopathy 2024",
      patientConcerns: "Worried about losing vision",
    },
    medicalHistory: {
      general: "Type 2 diabetes since 2014, hypertension",
      medications: "Metformin 1g BD, Losartan 50mg OD",
      allergies: "Sulfa drugs",
      conditions: "Diabetes, hypertension",
      surgeries: "None",
      familyHistory: "Father had glaucoma",
    },
    ocularHistory: {
      conditions: "Background diabetic retinopathy",
      surgery: "None",
      correction: "Reading glasses +2.00",
      lastExam: "May 2025",
      other: "",
    },
    examination: examFor("+0.50", "+0.75", "-0.50", "-0.25"),
    diagnoses: [
      { description: "Mild non-proliferative diabetic retinopathy", eye: "ou", code: "E11.319" },
      { description: "Presbyopia", eye: "ou", code: "H52.4" },
    ],
    findings: "Few dot haemorrhages in both posterior poles, no macular oedema.",
    assessment: "Stable mild NPDR with presbyopia.",
    managementPlan: "Maintain glycaemic control, review in 12 months, retinal photos filed.",
    followUpDate: daysAgo(-363),
    clinicalNotes: "Counselled on HbA1c targets.",
    createdAt: isoDaysAgo(2, 10),
  },
  {
    id: "v3",
    visitNumber: "VIS-2026-0452",
    patientId: "p8",
    clinicianId: "u2",
    date: t,
    status: "draft",
    chiefComplaint: {
      reason: "Eye strain and double vision when tired",
      symptoms: "Intermittent diplopia at near",
      duration: "6 weeks",
      previousEyeProblems: "None",
      patientConcerns: "Long shifts on the hotel front desk",
    },
    medicalHistory: {
      general: "Healthy",
      medications: "None",
      allergies: "None",
      conditions: "None",
      surgeries: "None",
      familyHistory: "Nil significant",
    },
    ocularHistory: {
      conditions: "None",
      surgery: "None",
      correction: "None",
      lastExam: "First examination",
      other: "",
    },
    examination: examFor("-0.50", "-0.25", "-0.25", "0.00"),
    diagnoses: [{ description: "Convergence insufficiency", eye: "ou" }],
    findings: "Reduced near point of convergence at 14cm.",
    assessment: "Convergence insufficiency, awaiting orthoptic exercises plan.",
    managementPlan: "",
    followUpDate: null,
    clinicalNotes: "Draft — pending completion after pencil push-up trial.",
    createdAt: isoDaysAgo(0, 9),
  },
];

export const prescriptions: Prescription[] = [
  {
    id: "rx1",
    prescriptionNumber: "RX-2026-0331",
    patientId: "p1",
    visitId: "v1",
    clinicianId: "u2",
    date: t,
    eyes: { od: rx("-2.25", "-0.75", "178"), os: rx("-2.50", "-1.00", "008") },
    pd: "62",
    lensType: "Single vision",
    lensMaterial: "Polycarbonate 1.59",
    lensCoating: "Anti-reflective + blue filter",
    frameInfo: "Ray-Ban RB5154 Havana, 51-21-145",
    notes: "Full-time wear.",
    createdAt: isoDaysAgo(0, 9),
  },
  {
    id: "rx2",
    prescriptionNumber: "RX-2026-0328",
    patientId: "p3",
    visitId: "v2",
    clinicianId: "u2",
    date: daysAgo(2),
    eyes: {
      od: rx("+0.50", "-0.50", "180", "+2.00", "6/6"),
      os: rx("+0.75", "-0.25", "005", "+2.00", "6/6"),
    },
    pd: "60",
    lensType: "Progressive",
    lensMaterial: "CR-39 1.50",
    lensCoating: "Hard coat + AR",
    frameInfo: "Practice house frame, metal full rim",
    notes: "Explained adaptation period for progressives.",
    createdAt: isoDaysAgo(2, 11),
  },
  {
    id: "rx3",
    prescriptionNumber: "RX-2026-0320",
    patientId: "p6",
    clinicianId: "u1",
    date: daysAgo(7),
    eyes: { od: rx("-1.75", "-0.50", "170"), os: rx("-2.00", "-0.25", "010") },
    pd: "64",
    lensType: "Contact lens",
    lensMaterial: "Silicone hydrogel",
    lensCoating: "n/a",
    contactLens: {
      brand: "Acuvue Oasys",
      baseCurve: "8.4",
      diameter: "14.0",
      power: "-1.75 / -2.00",
      replacement: "Monthly",
    },
    notes: "Reviewed insertion and removal technique.",
    createdAt: isoDaysAgo(7, 10),
  },
  {
    id: "rx4",
    prescriptionNumber: "RX-2026-0311",
    patientId: "p9",
    clinicianId: "u1",
    date: daysAgo(9),
    eyes: {
      od: rx("+1.25", "-0.75", "085", "+2.50"),
      os: rx("+1.00", "-0.50", "095", "+2.50"),
    },
    pd: "63",
    lensType: "Bifocal",
    lensMaterial: "CR-39 1.50",
    lensCoating: "Hard coat",
    frameInfo: "Titanium half rim",
    notes: "Post-cataract left eye, stable.",
    createdAt: isoDaysAgo(9, 15),
  },
];

export const invoices: Invoice[] = [
  {
    id: "i1",
    invoiceNumber: "INV-2026-1044",
    patientId: "p1",
    date: t,
    items: [
      { id: "ii1", description: "Comprehensive eye examination", serviceCode: "EXAM", quantity: 1, unitPrice: 2500, discount: 0 },
      { id: "ii2", description: "Ray-Ban RB5154 frame", productId: "pr1", quantity: 1, unitPrice: 18500, discount: 1500 },
      { id: "ii3", description: "Polycarbonate AR lenses (pair)", productId: "pr4", quantity: 1, unitPrice: 9500, discount: 0 },
    ],
    taxRate: 16,
    status: "partially_paid",
    insuranceClaimId: "cl1",
    createdBy: "u4",
    createdAt: isoDaysAgo(0, 10),
  },
  {
    id: "i2",
    invoiceNumber: "INV-2026-1043",
    patientId: "p3",
    date: daysAgo(2),
    items: [
      { id: "ii4", description: "Diabetic retinal screening", serviceCode: "RETSCR", quantity: 1, unitPrice: 3500, discount: 0 },
      { id: "ii5", description: "Progressive lenses (pair)", productId: "pr5", quantity: 1, unitPrice: 16800, discount: 800 },
    ],
    taxRate: 16,
    status: "paid",
    createdBy: "u4",
    createdAt: isoDaysAgo(2, 11),
  },
  {
    id: "i3",
    invoiceNumber: "INV-2026-1042",
    patientId: "p6",
    date: daysAgo(7),
    items: [
      { id: "ii6", description: "Contact lens fitting", serviceCode: "CLFIT", quantity: 1, unitPrice: 3000, discount: 0 },
      { id: "ii7", description: "Acuvue Oasys monthly (6 pack)", productId: "pr7", quantity: 2, unitPrice: 4200, discount: 0 },
    ],
    taxRate: 16,
    status: "paid",
    createdBy: "u4",
    createdAt: isoDaysAgo(7, 10),
  },
  {
    id: "i4",
    invoiceNumber: "INV-2026-1041",
    patientId: "p9",
    date: daysAgo(9),
    items: [
      { id: "ii8", description: "Follow-up consultation", serviceCode: "FUP", quantity: 1, unitPrice: 1500, discount: 0 },
      { id: "ii9", description: "Bifocal lenses (pair)", productId: "pr6", quantity: 1, unitPrice: 12400, discount: 0 },
      { id: "ii10", description: "Titanium half rim frame", productId: "pr2", quantity: 1, unitPrice: 9800, discount: 0 },
    ],
    taxRate: 16,
    status: "unpaid",
    createdBy: "u4",
    createdAt: isoDaysAgo(9, 15),
  },
  {
    id: "i5",
    invoiceNumber: "INV-2026-1045",
    patientId: "p5",
    date: t,
    items: [
      { id: "ii11", description: "Spectacle comfort review", serviceCode: "REV", quantity: 1, unitPrice: 1000, discount: 0 },
      { id: "ii12", description: "Lens cleaning kit", productId: "pr8", quantity: 1, unitPrice: 850, discount: 0 },
    ],
    taxRate: 16,
    status: "paid",
    createdBy: "u4",
    createdAt: isoDaysAgo(0, 8),
  },
  {
    id: "i6",
    invoiceNumber: "INV-2026-1040",
    patientId: "p4",
    date: daysAgo(14),
    items: [
      { id: "ii13", description: "Eye examination", serviceCode: "EXAM", quantity: 1, unitPrice: 2500, discount: 250 },
    ],
    taxRate: 16,
    status: "unpaid",
    createdBy: "u3",
    createdAt: isoDaysAgo(14, 12),
  },
  {
    id: "i7",
    invoiceNumber: "INV-2026-1046",
    patientId: "p8",
    date: t,
    items: [
      { id: "ii14", description: "Binocular vision assessment", serviceCode: "BVA", quantity: 1, unitPrice: 4000, discount: 0 },
    ],
    taxRate: 16,
    status: "draft",
    createdBy: "u4",
    createdAt: isoDaysAgo(0, 11),
  },
];

export const payments: Payment[] = [
  {
    id: "pay1",
    receiptNumber: "RCP-2026-2088",
    invoiceId: "i1",
    patientId: "p1",
    amount: 15000,
    method: "mpesa",
    reference: "SJ84KD21LP",
    date: isoDaysAgo(0, 10),
    receivedBy: "u4",
    status: "confirmed",
  },
  {
    id: "pay2",
    receiptNumber: "RCP-2026-2085",
    invoiceId: "i2",
    patientId: "p3",
    amount: 22968,
    method: "cash",
    date: isoDaysAgo(2, 11),
    receivedBy: "u4",
    status: "confirmed",
  },
  {
    id: "pay3",
    receiptNumber: "RCP-2026-2079",
    invoiceId: "i3",
    patientId: "p6",
    amount: 13224,
    method: "card",
    reference: "AUTH-449182",
    date: isoDaysAgo(7, 10),
    receivedBy: "u4",
    status: "confirmed",
  },
  {
    id: "pay4",
    receiptNumber: "RCP-2026-2089",
    invoiceId: "i5",
    patientId: "p5",
    amount: 2146,
    method: "mpesa",
    reference: "SJ90RT55QW",
    date: isoDaysAgo(0, 8),
    receivedBy: "u4",
    status: "confirmed",
  },
  {
    id: "pay5",
    receiptNumber: "RCP-2026-2072",
    invoiceId: "i4",
    patientId: "p9",
    amount: 5000,
    method: "bank_transfer",
    reference: "KCB-77120",
    date: isoDaysAgo(9, 16),
    receivedBy: "u4",
    status: "voided",
    notes: "Voided — transfer reversed by bank.",
  },
];

export const claims: InsuranceClaim[] = [
  {
    id: "cl1",
    claimNumber: "CLM-2026-0142",
    providerId: "ins2",
    patientId: "p1",
    invoiceId: "i1",
    memberNumber: "AAR-884221",
    policyNumber: "POL-AAR-22118",
    claimedAmount: 18000,
    approvedAmount: 12000,
    patientCopay: 6000,
    status: "partially_approved",
    submittedAt: t,
    notes: "Frame benefit capped at KES 12,000.",
  },
  {
    id: "cl2",
    claimNumber: "CLM-2026-0138",
    providerId: "ins1",
    patientId: "p2",
    invoiceId: "i6",
    memberNumber: "NHIF-5521884",
    policyNumber: "POL-NHIF-5521",
    claimedAmount: 2250,
    approvedAmount: 0,
    patientCopay: 0,
    status: "submitted",
    submittedAt: daysAgo(10),
  },
  {
    id: "cl3",
    claimNumber: "CLM-2026-0131",
    providerId: "ins3",
    patientId: "p5",
    invoiceId: "i5",
    memberNumber: "JUB-772100",
    policyNumber: "POL-JUB-9921",
    claimedAmount: 1850,
    approvedAmount: 1480,
    patientCopay: 370,
    status: "paid",
    submittedAt: daysAgo(4),
  },
  {
    id: "cl4",
    claimNumber: "CLM-2026-0144",
    providerId: "ins2",
    patientId: "p8",
    invoiceId: "i7",
    memberNumber: "AAR-110552",
    policyNumber: "POL-AAR-33891",
    claimedAmount: 4000,
    approvedAmount: 0,
    patientCopay: 0,
    status: "draft",
    submittedAt: null,
  },
];

export const suppliers: Supplier[] = [
  {
    id: "s1",
    name: "Optica Kenya Ltd",
    contactPerson: "Njeri Waweru",
    phone: "0722 881 445",
    email: "orders@opticakenya.co.ke",
    address: "Industrial Area, Nairobi",
    productsSupplied: "Designer frames, sunglasses",
    notes: "30-day credit terms.",
  },
  {
    id: "s2",
    name: "Nairobi Lens Works",
    contactPerson: "Samuel Kiarie",
    phone: "0733 220 118",
    email: "sales@nairobilens.co.ke",
    address: "Ngong Road, Nairobi",
    productsSupplied: "Single vision, bifocal and progressive lenses",
    notes: "48-hour surfacing turnaround.",
  },
  {
    id: "s3",
    name: "VisionCare Distributors",
    contactPerson: "Aisha Mohamed",
    phone: "0711 445 902",
    email: "info@visioncare.co.ke",
    address: "Mombasa Road, Nairobi",
    productsSupplied: "Contact lenses, solutions, eye drops",
  },
  {
    id: "s4",
    name: "EyeTech Supplies",
    contactPerson: "Collins Otieno",
    phone: "0798 114 220",
    email: "collins@eyetech.co.ke",
    address: "Eldoret",
    productsSupplied: "Accessories, cleaning kits, cases",
  },
];

export const products: Product[] = [
  { id: "pr1", sku: "FRM-RB5154", name: "Ray-Ban RB5154 Clubmaster", category: "frames", brand: "Ray-Ban", supplierId: "s1", costPrice: 11000, sellingPrice: 18500, quantity: 6, reorderLevel: 3, location: "Display A1", status: "active" },
  { id: "pr2", sku: "FRM-TI220", name: "Titanium Half Rim TI-220", category: "frames", brand: "Lumin", supplierId: "s1", costPrice: 5200, sellingPrice: 9800, quantity: 2, reorderLevel: 4, location: "Display A2", status: "active" },
  { id: "pr3", sku: "FRM-KID11", name: "Flexi Kids Frame", category: "frames", brand: "Kiddo", supplierId: "s1", costPrice: 1800, sellingPrice: 4500, quantity: 14, reorderLevel: 5, location: "Display B1", status: "active" },
  { id: "pr4", sku: "LNS-PC159AR", name: "Polycarbonate 1.59 AR (pair)", category: "lenses", brand: "Nairobi Lens", supplierId: "s2", costPrice: 4800, sellingPrice: 9500, quantity: 22, reorderLevel: 10, location: "Store S1", status: "active" },
  { id: "pr5", sku: "LNS-PROG150", name: "Progressive CR-39 1.50 (pair)", category: "lenses", brand: "Nairobi Lens", supplierId: "s2", costPrice: 9200, sellingPrice: 16800, quantity: 8, reorderLevel: 6, location: "Store S1", status: "active" },
  { id: "pr6", sku: "LNS-BIF150", name: "Bifocal CR-39 1.50 (pair)", category: "lenses", brand: "Nairobi Lens", supplierId: "s2", costPrice: 6100, sellingPrice: 12400, quantity: 3, reorderLevel: 6, location: "Store S1", status: "active" },
  { id: "pr7", sku: "CL-OASYS6", name: "Acuvue Oasys Monthly (6 pack)", category: "contact_lenses", brand: "Johnson & Johnson", supplierId: "s3", costPrice: 2400, sellingPrice: 4200, quantity: 18, reorderLevel: 8, location: "Store S2", status: "active" },
  { id: "pr8", sku: "ACC-CLEAN1", name: "Lens Cleaning Kit", category: "accessories", brand: "EyeTech", supplierId: "s4", costPrice: 380, sellingPrice: 850, quantity: 40, reorderLevel: 12, location: "Counter C1", status: "active" },
  { id: "pr9", sku: "ECP-ARTT10", name: "Artificial Tears 10ml", category: "eye_care", brand: "Optrex", supplierId: "s3", costPrice: 420, sellingPrice: 950, quantity: 5, reorderLevel: 15, location: "Counter C2", status: "active" },
  { id: "pr10", sku: "ACC-CASE22", name: "Hard Spectacle Case", category: "accessories", brand: "EyeTech", supplierId: "s4", costPrice: 200, sellingPrice: 600, quantity: 60, reorderLevel: 20, location: "Counter C1", status: "active" },
  { id: "pr11", sku: "CL-SOLN360", name: "Multipurpose Solution 360ml", category: "contact_lenses", brand: "Renu", supplierId: "s3", costPrice: 780, sellingPrice: 1500, quantity: 4, reorderLevel: 10, location: "Store S2", status: "active" },
  { id: "pr12", sku: "FRM-VNT09", name: "Vintage Acetate VT-09", category: "frames", brand: "Amani House", supplierId: "s1", costPrice: 3200, sellingPrice: 7500, quantity: 0, reorderLevel: 4, location: "Display A3", status: "discontinued" },
];

export const inventoryTransactions: InventoryTransaction[] = [
  { id: "it1", productId: "pr1", type: "stock_in", quantity: 6, reason: "Purchase order OPT-2211", reference: "PO-2211", date: isoDaysAgo(12, 9), recordedBy: "u5" },
  { id: "it2", productId: "pr4", type: "stock_out", quantity: 1, reason: "Sold on INV-2026-1044", reference: "INV-2026-1044", date: isoDaysAgo(0, 10), recordedBy: "u4" },
  { id: "it3", productId: "pr9", type: "stock_out", quantity: 10, reason: "Dispensed to patients", date: isoDaysAgo(3, 15), recordedBy: "u5" },
  { id: "it4", productId: "pr6", type: "adjustment", quantity: -1, reason: "Damaged during edging", date: isoDaysAgo(5, 14), recordedBy: "u5" },
  { id: "it5", productId: "pr7", type: "stock_in", quantity: 24, reason: "Purchase order VC-9921", reference: "PO-9921", date: isoDaysAgo(20, 10), recordedBy: "u5" },
  { id: "it6", productId: "pr2", type: "stock_out", quantity: 1, reason: "Sold on INV-2026-1041", reference: "INV-2026-1041", date: isoDaysAgo(9, 15), recordedBy: "u4" },
  { id: "it7", productId: "pr11", type: "stock_out", quantity: 6, reason: "Retail counter sales", date: isoDaysAgo(6, 17), recordedBy: "u5" },
];

export const auditLogs: AuditLog[] = [
  { id: "al1", userId: "u4", action: "Payment recorded", module: "payments", record: "RCP-2026-2088", timestamp: isoDaysAgo(0, 10), description: "KES 15,000 received via M-Pesa for INV-2026-1044." },
  { id: "al2", userId: "u2", action: "Prescription created", module: "prescriptions", record: "RX-2026-0331", timestamp: isoDaysAgo(0, 9), description: "Prescription issued for Wanjiku Kamau." },
  { id: "al3", userId: "u3", action: "Patient created", module: "patients", record: "AE-2026-0194", timestamp: isoDaysAgo(12, 11), description: "Patricia Mwangi registered from school screening." },
  { id: "al4", userId: "u5", action: "Inventory adjusted", module: "inventory", record: "LNS-BIF150", timestamp: isoDaysAgo(5, 14), description: "1 pair written off as damaged during edging." },
  { id: "al5", userId: "u1", action: "User created", module: "administration", record: "jbarasa", timestamp: isoDaysAgo(150, 9), description: "Store officer account created." },
  { id: "al6", userId: "u4", action: "Invoice created", module: "invoices", record: "INV-2026-1046", timestamp: isoDaysAgo(0, 11), description: "Draft invoice raised for binocular vision assessment." },
  { id: "al7", userId: "u2", action: "Visit completed", module: "clinical", record: "VIS-2026-0451", timestamp: isoDaysAgo(0, 9), description: "Eye examination completed for Wanjiku Kamau." },
  { id: "al8", userId: "u4", action: "Payment voided", module: "payments", record: "RCP-2026-2072", timestamp: isoDaysAgo(8, 12), description: "Bank transfer reversed, receipt voided." },
];

export const practiceSettings: PracticeSettings = {
  practiceName: "Amani Eye Centre",
  tagline: "Clear sight, cared for",
  address: "Waiyaki Way, Sunrise Plaza, 2nd Floor",
  county: "Nairobi",
  town: "Westlands",
  phone: "0722 145 880",
  email: "frontdesk@amanieye.co.ke",
  currency: "KES",
  taxRate: 16,
  taxLabel: "VAT",
  invoicePrefix: "INV-2026-",
  receiptPrefix: "RCP-2026-",
  prescriptionPrefix: "RX-2026-",
  registrationNumber: "OB/OPT/2019/4471",
  kraPin: "P051884472K",
};
