/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as PurchasesNewRouteImport } from './routes/purchases.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomersRoute,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvoicesRoute,
} as any)
const PurchasesNewRoute = PurchasesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PurchasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/customers': typeof CustomersRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/purchases': typeof PurchasesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/service': typeof ServiceRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/suppliers': typeof SuppliersRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/purchases/new': typeof PurchasesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/customers': typeof CustomersRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/purchases': typeof PurchasesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/service': typeof ServiceRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/suppliers': typeof SuppliersRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/purchases/new': typeof PurchasesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/customers': typeof CustomersRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/purchases': typeof PurchasesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/service': typeof ServiceRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/suppliers': typeof SuppliersRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/purchases/new': typeof PurchasesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customers'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/payments'
    | '/purchases'
    | '/reports'
    | '/service'
    | '/settings'
    | '/stock'
    | '/suppliers'
    | '/customers/$id'
    | '/customers/new'
    | '/invoices/$id'
    | '/purchases/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/customers'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/payments'
    | '/purchases'
    | '/reports'
    | '/service'
    | '/settings'
    | '/stock'
    | '/suppliers'
    | '/customers/$id'
    | '/customers/new'
    | '/invoices/$id'
    | '/purchases/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customers'
    | '/inventory'
    | '/invoices'
    | '/login'
    | '/payments'
    | '/purchases'
    | '/reports'
    | '/service'
    | '/settings'
    | '/stock'
    | '/suppliers'
    | '/customers/$id'
    | '/customers/new'
    | '/invoices/$id'
    | '/purchases/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  PurchasesRoute: typeof PurchasesRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  ServiceRoute: typeof ServiceRoute
  SettingsRoute: typeof SettingsRoute
  StockRoute: typeof StockRoute
  SuppliersRoute: typeof SuppliersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/purchases/new': {
      id: '/purchases/new'
      path: '/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof PurchasesNewRouteImport
      parentRoute: typeof PurchasesRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersNewRoute: typeof CustomersNewRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
  CustomersNewRoute: CustomersNewRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesIdRoute: typeof InvoicesIdRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesIdRoute: InvoicesIdRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface PurchasesRouteChildren {
  PurchasesNewRoute: typeof PurchasesNewRoute
}

const PurchasesRouteChildren: PurchasesRouteChildren = {
  PurchasesNewRoute: PurchasesNewRoute,
}

const PurchasesRouteWithChildren = PurchasesRoute._addFileChildren(
  PurchasesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CustomersRoute: CustomersRouteWithChildren,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  PurchasesRoute: PurchasesRouteWithChildren,
  ReportsRoute: ReportsRoute,
  ServiceRoute: ServiceRoute,
  SettingsRoute: SettingsRoute,
  StockRoute: StockRoute,
  SuppliersRoute: SuppliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
